name: push format

on:
  push:
    branches:
      - main

jobs:
  push_format:
    permissions:
      actions: write
      checks: write
      contents: write
      issues: write
      repository-projects: write
      pull-requests: write
    runs-on: ubuntu-latest
    # continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.ref_name}}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Black
        run: pip install black

      - name: Run Black
        # run: black $(git ls-files '*.py')
        run: black .

      - name: Commit Back
        continue-on-error: true
        id: commitback
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Format code"
      
      - name: Create Pull Request
        if: steps.commitback.outcome == 'success'
        continue-on-error: true
        uses: peter-evans/create-pull-request@v4
        with:
          commit_message: Apply Code Formatter Change
